In [2]:
import torch
import torch.nn as nn

batch_size = 32
feature_size = 128 

x = torch.rand(batch_size, feature_size)

In [3]:
x

tensor([[0.6828, 0.1631, 0.2930,  ..., 0.4959, 0.8064, 0.9331],
        [0.8069, 0.9690, 0.2139,  ..., 0.0646, 0.7197, 0.0673],
        [0.8258, 0.1198, 0.7840,  ..., 0.1507, 0.2348, 0.4673],
        ...,
        [0.8257, 0.0345, 0.2853,  ..., 0.0035, 0.5261, 0.8097],
        [0.8108, 0.0037, 0.3900,  ..., 0.3725, 0.4544, 0.3976],
        [0.9681, 0.9737, 0.6177,  ..., 0.5118, 0.2648, 0.1053]])

In [4]:
in_features = 128
out_features = 64
layer = nn.Linear(in_features, out_features, bias=True)

In [5]:
layer

Linear(in_features=128, out_features=64, bias=True)

In [6]:
layer.weight.shape

torch.Size([64, 128])

In [7]:
x = torch.rand(8, 128)
output = layer(x)

In [9]:
output

tensor([[-4.6097e-01,  2.5364e-01, -3.0493e-01, -8.3769e-02, -1.7225e-01,
         -4.0375e-02,  3.3306e-01,  4.1602e-01,  5.1499e-01, -4.0380e-01,
         -7.1488e-02, -6.2799e-01, -5.4174e-01, -3.2508e-01, -1.3965e-01,
          1.2884e-01, -3.6300e-02,  4.2453e-01, -7.2954e-02, -4.5699e-01,
          7.6925e-02,  2.9446e-01,  1.9086e-01, -1.7215e-01, -4.5839e-01,
          8.2610e-01,  4.8344e-01,  4.7202e-01,  6.1189e-01,  2.5614e-01,
          1.8071e-01,  1.8434e-01,  3.3371e-01,  2.9522e-02,  3.6208e-01,
         -8.9819e-02,  1.1613e-01, -2.1760e-01,  4.0662e-01, -3.2141e-01,
          9.4885e-03, -2.0190e-01,  4.6126e-01, -2.1529e-01,  4.0823e-01,
          1.5791e-01, -1.2949e-01, -1.9354e-01,  1.3291e-01, -6.7900e-01,
          2.4545e-01, -3.8074e-02, -4.2377e-01, -5.2319e-01,  4.6036e-01,
          3.6575e-01,  4.3090e-01, -5.0608e-01, -1.7950e-01,  6.2847e-01,
         -3.8765e-02,  2.0048e-01,  6.4281e-02,  6.9703e-02],
        [-4.7128e-01,  1.3872e-01,  2.8916e-01,  5

In [8]:
output_2 = x @ layer.weight.t() + layer.bias

In [10]:
output_2

tensor([[-4.6097e-01,  2.5364e-01, -3.0493e-01, -8.3769e-02, -1.7225e-01,
         -4.0375e-02,  3.3306e-01,  4.1602e-01,  5.1499e-01, -4.0380e-01,
         -7.1488e-02, -6.2799e-01, -5.4174e-01, -3.2508e-01, -1.3965e-01,
          1.2884e-01, -3.6300e-02,  4.2453e-01, -7.2954e-02, -4.5699e-01,
          7.6925e-02,  2.9446e-01,  1.9086e-01, -1.7215e-01, -4.5839e-01,
          8.2610e-01,  4.8344e-01,  4.7202e-01,  6.1189e-01,  2.5614e-01,
          1.8071e-01,  1.8434e-01,  3.3371e-01,  2.9522e-02,  3.6208e-01,
         -8.9819e-02,  1.1613e-01, -2.1760e-01,  4.0662e-01, -3.2141e-01,
          9.4885e-03, -2.0190e-01,  4.6126e-01, -2.1529e-01,  4.0823e-01,
          1.5791e-01, -1.2949e-01, -1.9354e-01,  1.3291e-01, -6.7900e-01,
          2.4545e-01, -3.8074e-02, -4.2377e-01, -5.2319e-01,  4.6036e-01,
          3.6575e-01,  4.3090e-01, -5.0608e-01, -1.7950e-01,  6.2847e-01,
         -3.8765e-02,  2.0048e-01,  6.4281e-02,  6.9703e-02],
        [-4.7128e-01,  1.3872e-01,  2.8916e-01,  5

In [11]:
x = torch.rand(8, 128)
act_fn = torch.nn.Sigmoid()

out = act_fn(x)
out.shape

torch.Size([8, 128])

In [12]:
x = torch.rand(8, 128)
act_fn = torch.nn.Tanh()

out = act_fn(x)
out.shape

torch.Size([8, 128])

In [13]:
x = torch.rand(8, 128)
act_fn = torch.nn.ReLU()

out = act_fn(x)
out.shape

torch.Size([8, 128])

In [17]:
x = torch.rand(1, 20)
softmax = torch.nn.Softmax(dim=1)

pred_proba = softmax(x)
pred_proba.shape


torch.Size([1, 20])

In [19]:
print('Sum of logits :', torch.sum(x, dim=1).item())
print('Sum of probabilities :', torch.sum(pred_proba, dim=1).item())

Sum of logits : 6.829951763153076
Sum of probabilities : 1.0


In [20]:
pred_proba

tensor([[0.0404, 0.0375, 0.0499, 0.0741, 0.0348, 0.0418, 0.0427, 0.0819, 0.0583,
         0.0507, 0.0415, 0.0528, 0.0417, 0.0810, 0.0416, 0.0384, 0.0602, 0.0488,
         0.0439, 0.0382]])

In [21]:
in_features = 128
out_features = 64

layer_1 = torch.nn.Linear(in_features, out_features, bias=True)
act_fn = torch.nn.Tanh()

In [22]:
in_features = 64
out_features = 16

layer_2 = torch.nn.Linear(in_features, out_features, bias=True)
act_fn_2 = torch.nn.Tanh()

In [23]:
in_features = 16
out_features = 1

layer_3 = torch.nn.Linear(in_features, out_features, bias=True)
act_fn_3 = torch.nn.Sigmoid()

In [26]:
x = torch.rand(8, 128)

out_1 = act_fn(layer_1(x))
out_1.shape

torch.Size([8, 64])

In [27]:
out_2 = act_fn_2(layer_2(out_1))
out_2.shape

torch.Size([8, 16])

In [28]:
out_3 = act_fn_3(layer_3(out_2))
out_3.shape

torch.Size([8, 1])

In [29]:
out_3

tensor([[0.4939],
        [0.5039],
        [0.5304],
        [0.5230],
        [0.5291],
        [0.5020],
        [0.5191],
        [0.5246]], grad_fn=<SigmoidBackward0>)

In [30]:
model = nn.Sequential(
    torch.nn.Linear(128, 64, bias=True),
    torch.nn.Tanh(),
    torch.nn.Linear(64, 16, bias=True),
    torch.nn.Tanh(),
    torch.nn.Linear(16, 1, bias=True),
    torch.nn.Sigmoid()
)

In [31]:
x = torch.rand(32, 128)

out = model(x)

In [32]:
out

tensor([[0.4334],
        [0.4458],
        [0.4285],
        [0.4201],
        [0.4265],
        [0.4519],
        [0.4398],
        [0.4526],
        [0.4148],
        [0.4004],
        [0.4299],
        [0.4150],
        [0.4329],
        [0.4112],
        [0.4168],
        [0.4147],
        [0.4255],
        [0.3967],
        [0.4299],
        [0.4289],
        [0.4384],
        [0.4272],
        [0.4423],
        [0.4288],
        [0.3925],
        [0.4419],
        [0.4057],
        [0.4192],
        [0.4307],
        [0.4127],
        [0.4310],
        [0.4160]], grad_fn=<SigmoidBackward0>)

In [33]:
class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.layers = nn.Sequential(
            torch.nn.Linear(128, 64, bias=True),
            torch.nn.Tanh(),
            torch.nn.Linear(64, 16, bias=True),
            torch.nn.Tanh(),
            torch.nn.Linear(16, 1, bias=True),
            torch.nn.Sigmoid()
        )
    
    def forward(self, x):
        return self.layers(x)

In [34]:
x = torch.rand(32, 128)
model = Model()
out = model(x)

In [35]:
model

Model(
  (layers): Sequential(
    (0): Linear(in_features=128, out_features=64, bias=True)
    (1): Tanh()
    (2): Linear(in_features=64, out_features=16, bias=True)
    (3): Tanh()
    (4): Linear(in_features=16, out_features=1, bias=True)
    (5): Sigmoid()
  )
)

In [36]:
!pip install torchsummary

In [37]:
from torchsummary import summary

summary(model, (128,))

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                   [-1, 64]           8,256
              Tanh-2                   [-1, 64]               0
            Linear-3                   [-1, 16]           1,040
              Tanh-4                   [-1, 16]               0
            Linear-5                    [-1, 1]              17
           Sigmoid-6                    [-1, 1]               0
Total params: 9,313
Trainable params: 9,313
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.04
Estimated Total Size (MB): 0.04
----------------------------------------------------------------
