In [2]:
!pip install torch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.1/62.1 MB 22.2 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 20.6 MB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 13.1 MB/s eta 0:00:00


In [3]:
import numpy as np
import torch

In [5]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [6]:
x_data

tensor([[1, 2],
        [3, 4]])

In [8]:
x_data.dtype

torch.int64

In [10]:
shape = (2, 3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"One Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8617, 0.6026, 0.8751],
        [0.1910, 0.1186, 0.5599]]) 

One Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
data = [[1, 2], [3, 4]]
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [13]:
x_np

tensor([[1, 2],
        [3, 4]])

In [14]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data, dtype=torch.float32)

In [16]:
x_data

tensor([[1., 2.],
        [3., 4.]])

In [15]:
x_data.dtype

torch.float32

In [17]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data, dtype=torch.uint8)

In [18]:
x_data

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [19]:
x_data = x_data.to(dtype=torch.float32)

In [20]:
x_data

tensor([[1., 2.],
        [3., 4.]])

In [21]:
torch.cuda.is_available()

False

In [23]:
x_data = x_data.to("cuda")

AssertionError: Torch not compiled with CUDA enabled

In [24]:
x_data = x_data.cpu()
x_data = x_data.to("cpu")

In [25]:
x_data.device

device(type='cpu')

### Tensor 활용 연산

In [26]:
tensor = torch.ones(4, 4)
print('First row: ', tensor[0])
print('First column: ', tensor[:, 0])
print('Last column: ', tensor[:, -1])

First row:  tensor([1., 1., 1., 1.])
First column:  tensor([1., 1., 1., 1.])
Last column:  tensor([1., 1., 1., 1.])


In [27]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
t1

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [28]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

In [29]:
y1, y2

(tensor([[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]),
 tensor([[4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.],
         [4., 4., 4., 4.]]))

In [30]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)

In [31]:
z1, z2

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]))

In [32]:
tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [33]:
tensor.add_(5)

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

In [34]:
tensor

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])